# Generated by Django 3.2.1 on 2021-05-06 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('hasil_hitung', models.FloatField(default='', max_length=200)),
                ('id_user', models.IntegerField(default='', max_length=11)),
            ],
        ),
    ]
